export const metadata = {
  title: "Terms of Service — TrendSpark",
  description: "Terms of Service for the TrendSpark content tool.",
  robots: { index: false, follow: false },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0a0e1a] px-6 py-16 text-slate-300">
      <div className="mx-auto max-w-3xl space-y-6 leading-relaxed">
        <header>
          <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
          <p className="mt-2 text-sm text-slate-500">Last updated: June 17, 2026</p>
        </header>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">1. Overview</h2>
          <p>
            TrendSpark is a tool that helps a creator turn trending news into short
            vertical videos with an AI voiceover, and publish them to that creator&apos;s
            own TikTok account. By using TrendSpark you agree to these terms. If you do
            not agree, do not use the service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">2. Your TikTok account</h2>
          <p>
            TrendSpark connects to TikTok using TikTok&apos;s official authorization
            (OAuth). You grant access to your own account, and you can revoke it at any
            time in your TikTok settings. TrendSpark only posts to the account you
            authorize. You are responsible for the content you publish and for following
            TikTok&apos;s Terms of Service and Community Guidelines, including the rules on
            labeling AI-generated content.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">3. Acceptable use</h2>
          <p>
            You agree not to use TrendSpark to create or post content that is unlawful,
            misleading, infringing, hateful, or that violates the rules of any platform it
            is published to. You are responsible for reviewing content before it is made
            public.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">4. AI-generated content</h2>
          <p>
            Scripts, voiceovers, and visuals produced by TrendSpark are generated by
            automated models and may contain errors or inaccuracies. You should review
            content for accuracy and appropriateness before publishing, and disclose
            AI-generated content where required.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">5. Service provided as is</h2>
          <p>
            The service is provided on an &quot;as is&quot; and &quot;as available&quot;
            basis without warranties of any kind. We do not guarantee that the service
            will be uninterrupted, error free, or that any result, including reach or
            engagement on any platform, will be achieved.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">6. Limitation of liability</h2>
          <p>
            To the maximum extent permitted by law, TrendSpark and its operator are not
            liable for any indirect, incidental, or consequential damages arising from your
            use of the service.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">7. Changes</h2>
          <p>
            We may update these terms from time to time. Continued use of the service after
            an update means you accept the revised terms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-white">8. Contact</h2>
          <p>
            Questions about these terms can be sent to{" "}
            <a className="text-violet-400 underline" href="mailto:missara.lamine@gmail.com">
              missara.lamine@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
